"""VIPER CLI — Vulnerability Identification, Patching & Evaluation Robot."""

from __future__ import annotations

import asyncio
import time
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.table import Table

from viper import ViperError, __version__
from viper.config import ViperConfig
from viper.models.vulnerability import Severity, SnykReport
from viper.parsers.snyk_parser import SnykParser

app = typer.Typer(
    name="viper",
    help="VIPER — Vulnerability Identification, Patching & Evaluation Robot",
    no_args_is_help=True,
)
console = Console()

VIPER_BANNER = r"""[bold cyan]
 ╦  ╦╦╔═╗╔═╗╦═╗
 ╚╗╔╝║╠═╝║╣ ╠╦╝
  ╚╝ ╩╩  ╚═╝╩╚═[/bold cyan] [dim]v{}[/dim]
[dim]Vulnerability Identification, Patching & Evaluation Robot[/dim]
"""


def _load_config(config_path: Path | None) -> ViperConfig:
    if config_path:
        return ViperConfig.load(config_path)
    for p in [Path("viper.yaml"), Path("viper.yml")]:
        if p.exists():
            return ViperConfig.load(p)
    return ViperConfig()


def _run_scan_with_progress(
    project_dir: Path, config: ViperConfig
) -> SnykReport:
    """Run Snyk scan with a spinner."""
    with Progress(
        SpinnerColumn("dots"),
        TextColumn("[bold]{task.description}"),
        TimeElapsedColumn(),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task("Scanning all projects with Snyk (--all-projects)...", total=None)
        return SnykParser.run_scan(
            project_dir=project_dir,
            snyk_token=config.snyk.token or None,
            org=config.snyk.org or None,
        )


def _display_vulns(report: SnykReport, severity_filter: str | None = None) -> int:
    """Display vulnerabilities in a Rich table. Returns count displayed."""
    vulns = report.vulnerabilities
    if severity_filter:
        min_sev = Severity(severity_filter)
        vulns = [v for v in vulns if v.severity >= min_sev]

    vulns = SnykParser.deduplicate(vulns)

    if not vulns:
        console.print("[green]No vulnerabilities found![/green]")
        return 0

    table = Table(title=f"Vulnerabilities ({len(vulns)} found)", show_lines=True)
    table.add_column("Sev", style="bold", width=8)
    table.add_column("Package", min_width=20)
    table.add_column("Version", width=12)
    table.add_column("Title", min_width=30)
    table.add_column("Fix?", width=5)
    table.add_column("ID", style="dim", max_width=35)

    severity_colors = {
        Severity.critical: "red",
        Severity.high: "bright_red",
        Severity.medium: "yellow",
        Severity.low: "blue",
    }

    for v in sorted(vulns, key=lambda x: x.severity.rank, reverse=True):
        color = severity_colors.get(v.severity, "white")
        table.add_row(
            f"[{color}]{v.severity.value.upper()}[/{color}]",
            v.package_name,
            v.version,
            v.title,
            "[green]Y[/green]" if v.is_upgradable else "[red]N[/red]",
            v.id,
        )

    console.print(table)

    # Summary bar
    by_sev: dict[str, int] = {}
    for v in vulns:
        by_sev[v.severity.value] = by_sev.get(v.severity.value, 0) + 1
    parts = []
    for sev in ["critical", "high", "medium", "low"]:
        if sev in by_sev:
            color = severity_colors[Severity(sev)]
            parts.append(f"[{color}]{by_sev[sev]} {sev}[/{color}]")
    console.print(f"\n  {' | '.join(parts)}")

    return len(vulns)


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    version: bool = typer.Option(False, "--version", "-v", help="Show version"),
) -> None:
    if version:
        console.print(f"VIPER v{__version__}")
        raise typer.Exit()
    if ctx.invoked_subcommand is None:
        raise typer.Exit()


@app.command()
def init(
    output: Path = typer.Option(
        Path("viper.yaml"), "--output", "-o", help="Output path for config file"
    ),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing config"),
) -> None:
    """Create a viper.yaml configuration file."""
    import os

    if output.exists() and not force:
        console.print(f"[yellow]{output} already exists.[/yellow] Use --force to overwrite.")
        raise typer.Exit(1)

    config_content = """\
# VIPER Configuration
# Generated by `viper init`

snyk:
  token: "${SNYK_TOKEN}"  # reads from SNYK_TOKEN env var
  org: ""                  # your Snyk organization (optional)

gitlab:
  url: https://gitlab.com
  token: "${VIPER_GITLAB_TOKEN}"  # reads from VIPER_GITLAB_TOKEN env var
  project_id: ""                   # your GitLab project ID
  target_branch: main

ai:
  model: github_copilot/gpt-4o   # any LiteLLM-supported model
  temperature: 0.2
  max_tokens: 4096

agent:
  max_iterations: 30
  timeout_per_tool: 300
  blocked_commands:
    - "rm -rf /"
    - "sudo"
    - "chmod"
    - "mkfs"

settings:
  severity_threshold: medium   # low, medium, high, critical
  dry_run: false
"""
    output.write_text(config_content)
    console.print(f"[green]Created {output}[/green]")

    snyk_token = os.environ.get("SNYK_TOKEN", "")
    gitlab_token = os.environ.get("VIPER_GITLAB_TOKEN", "")

    if snyk_token:
        display = f"{snyk_token[:8]}..."
        console.print(f"  SNYK_TOKEN: [green]detected[/green] ({display})")
    else:
        console.print(
            "  SNYK_TOKEN: [red]not set[/red] — "
            "run [bold]export SNYK_TOKEN=<your-token>[/bold] or [bold]snyk auth[/bold]"
        )

    if gitlab_token:
        console.print(f"  VIPER_GITLAB_TOKEN: [green]detected[/green]")
    else:
        console.print("  VIPER_GITLAB_TOKEN: [dim]not set (needed for `viper mr` only)[/dim]")


@app.command()
def scan(
    project_dir: Optional[Path] = typer.Option(None, "--project-dir", "-p", help="Project directory to scan"),
    report_file: Optional[Path] = typer.Option(None, "--report-file", "-r", help="Existing Snyk JSON report"),
    severity: Optional[str] = typer.Option(None, "--severity", "-s", help="Minimum severity: low, medium, high, critical"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Path to viper.yaml"),
    output: str = typer.Option("table", "--output", "-o", help="Output format: table, json"),
) -> None:
    """Run Snyk scan and display vulnerabilities."""
    try:
        cfg = _load_config(config)

        if report_file:
            report = SnykParser.parse_file(report_file)
        else:
            target = project_dir or Path.cwd()
            report = _run_scan_with_progress(target, cfg)

        if output == "json":
            console.print_json(report.model_dump_json(indent=2))
        else:
            _display_vulns(report, severity)

    except ViperError as e:
        console.print(f"[red]Error:[/red] {e}")
        raise typer.Exit(1)


@app.command()
def fix(
    project_dir: Optional[Path] = typer.Option(None, "--project-dir", "-p", help="Project directory"),
    report_file: Optional[Path] = typer.Option(None, "--report-file", "-r", help="Existing Snyk JSON report"),
    severity: Optional[str] = typer.Option(None, "--severity", "-s", help="Minimum severity"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Path to viper.yaml"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show changes without applying"),
    verbose: bool = typer.Option(False, "--verbose", help="Show agent tool calls"),
    max_iterations: Optional[int] = typer.Option(None, "--max-iterations", help="Max agent loop iterations"),
) -> None:
    """Analyze and fix vulnerabilities using AI agent."""
    try:
        cfg = _load_config(config)
        if dry_run:
            cfg.dry_run = True
        if max_iterations:
            cfg.agent.max_iterations = max_iterations

        target_dir = project_dir or Path.cwd()

        if report_file:
            report = SnykParser.parse_file(report_file)
        else:
            report = _run_scan_with_progress(target_dir, cfg)

        if report.ok and not report.vulnerabilities:
            console.print("[green]No vulnerabilities found![/green]")
            raise typer.Exit()

        _display_vulns(report, severity)

        from viper.agent.loop import ViperAgent

        console.print()
        with Progress(
            SpinnerColumn("dots"),
            TextColumn("[bold]{task.description}"),
            TimeElapsedColumn(),
            console=console,
            transient=False,
        ) as progress:
            task = progress.add_task("AI agent analyzing and fixing vulnerabilities...", total=None)
            agent = ViperAgent(config=cfg, project_dir=target_dir, verbose=verbose)
            result = asyncio.run(agent.run_fix(report))
            progress.update(task, description="[green]Agent complete")

        if result.success:
            console.print(f"\n[green]Fix complete![/green] {result.summary}")
            if result.tests_passed is not None:
                status = "[green]passed[/green]" if result.tests_passed else "[red]failed[/red]"
                console.print(f"Tests: {status}")
            for change in result.changes:
                console.print(f"  Modified: {change.path}")
        else:
            console.print(f"\n[red]Fix failed:[/red] {result.summary}")
            raise typer.Exit(1)

    except ViperError as e:
        console.print(f"[red]Error:[/red] {e}")
        raise typer.Exit(1)


@app.command()
def report(
    project_dir: Optional[Path] = typer.Option(None, "--project-dir", "-p", help="Project directory"),
    report_file: Optional[Path] = typer.Option(None, "--report-file", "-r", help="Existing Snyk JSON report"),
    severity: Optional[str] = typer.Option(None, "--severity", "-s", help="Minimum severity"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Path to viper.yaml"),
    format: str = typer.Option("markdown", "--format", "-f", help="Output format: markdown, json"),
    output_file: Optional[Path] = typer.Option(None, "--output", "-o", help="Write report to file"),
) -> None:
    """Generate a vulnerability remediation report."""
    try:
        cfg = _load_config(config)

        if report_file:
            snyk_report = SnykParser.parse_file(report_file)
        else:
            target = project_dir or Path.cwd()
            snyk_report = _run_scan_with_progress(target, cfg)

        from viper.report_generator import ReportGenerator

        generator = ReportGenerator()
        if format == "json":
            content = generator.generate_json(snyk_report)
        else:
            content = generator.generate_markdown(snyk_report)

        if output_file:
            output_file.write_text(content)
            console.print(f"Report written to {output_file}")
        else:
            console.print(content)

    except ViperError as e:
        console.print(f"[red]Error:[/red] {e}")
        raise typer.Exit(1)


@app.command()
def mr(
    project_dir: Optional[Path] = typer.Option(None, "--project-dir", "-p", help="Project directory"),
    report_file: Optional[Path] = typer.Option(None, "--report-file", "-r", help="Existing Snyk JSON report"),
    severity: Optional[str] = typer.Option(None, "--severity", "-s", help="Minimum severity"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Path to viper.yaml"),
    target_branch: Optional[str] = typer.Option(None, "--target-branch", help="MR target branch"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show changes without creating MR"),
    verbose: bool = typer.Option(False, "--verbose", help="Show agent tool calls"),
) -> None:
    """Fix vulnerabilities and create a GitLab merge request."""
    try:
        cfg = _load_config(config)
        if dry_run:
            cfg.dry_run = True
        if target_branch:
            cfg.gitlab.target_branch = target_branch

        target_dir = project_dir or Path.cwd()

        if report_file:
            report = SnykParser.parse_file(report_file)
        else:
            report = _run_scan_with_progress(target_dir, cfg)

        if report.ok and not report.vulnerabilities:
            console.print("[green]No vulnerabilities found![/green]")
            raise typer.Exit()

        from viper.agent.loop import ViperAgent

        with Progress(
            SpinnerColumn("dots"),
            TextColumn("[bold]{task.description}"),
            TimeElapsedColumn(),
            console=console,
        ) as progress:
            progress.add_task("AI agent fixing vulnerabilities...", total=None)
            agent = ViperAgent(config=cfg, project_dir=target_dir, verbose=verbose)
            result = asyncio.run(agent.run_fix(report))

        if not result.success:
            console.print(f"[red]Fix failed:[/red] {result.summary}")
            raise typer.Exit(1)

        if cfg.dry_run:
            console.print("[yellow]Dry run — skipping MR creation[/yellow]")
            console.print(result.summary)
            raise typer.Exit()

        from viper.gitlab_integration import GitLabClient

        with Progress(
            SpinnerColumn("dots"),
            TextColumn("[bold]{task.description}"),
            TimeElapsedColumn(),
            console=console,
        ) as progress:
            progress.add_task("Creating GitLab merge request...", total=None)
            gl = GitLabClient(cfg.gitlab)
            mr_url = asyncio.run(gl.create_fix_mr(result, report))

        console.print(f"\n[green]Merge request created:[/green] {mr_url}")

    except ViperError as e:
        console.print(f"[red]Error:[/red] {e}")
        raise typer.Exit(1)


@app.command()
def auto(
    project_dir: Optional[Path] = typer.Option(None, "--project-dir", "-p", help="Project directory"),
    severity: Optional[str] = typer.Option(None, "--severity", "-s", help="Minimum severity"),
    config: Optional[Path] = typer.Option(None, "--config", "-c", help="Path to viper.yaml"),
    max_cycles: int = typer.Option(5, "--max-cycles", "-n", help="Max scan-fix-validate cycles"),
    verbose: bool = typer.Option(False, "--verbose", help="Show agent tool calls"),
    max_iterations: Optional[int] = typer.Option(None, "--max-iterations", help="Max agent iterations per cycle"),
) -> None:
    """Full auto-remediation loop: scan -> fix -> validate, repeat until clean."""
    try:
        cfg = _load_config(config)
        if max_iterations:
            cfg.agent.max_iterations = max_iterations

        target_dir = project_dir or Path.cwd()
        sev_threshold = severity or cfg.severity_threshold

        console.print(VIPER_BANNER.format(__version__))
        console.print(f"  Project:  [bold]{target_dir}[/bold]")
        console.print(f"  Severity: [bold]{sev_threshold}[/bold]+")
        console.print(f"  Cycles:   [bold]{max_cycles}[/bold] max")
        console.print()

        from viper.agent.loop import ViperAgent

        all_changes = []
        total_fixed = 0
        start_time = time.time()

        for cycle in range(1, max_cycles + 1):
            console.rule(
                f"[bold cyan]Cycle {cycle} of {max_cycles}[/bold cyan]",
                style="cyan",
            )

            # ── SCAN ──────────────────────────────────────────────
            console.print()
            with Progress(
                SpinnerColumn("dots"),
                TextColumn("[bold]{task.description}"),
                TimeElapsedColumn(),
                console=console,
                transient=True,
            ) as progress:
                progress.add_task(
                    f"[1/3] Scanning all projects with Snyk...", total=None
                )
                try:
                    report = SnykParser.run_scan(
                        project_dir=target_dir,
                        snyk_token=cfg.snyk.token or None,
                        org=cfg.snyk.org or None,
                    )
                except ViperError as e:
                    console.print(f"[red]Scan error:[/red] {e}")
                    raise typer.Exit(1)

            vulns = SnykParser.filter_by_severity(report, Severity(sev_threshold))
            vulns = SnykParser.deduplicate(vulns)

            if not vulns:
                console.print(
                    Panel(
                        "[bold green]Project is clean! No vulnerabilities found.[/bold green]",
                        border_style="green",
                    )
                )
                break

            console.print(
                f"  [bold]Found {len(vulns)} vulnerabilities[/bold] "
                f"(from {report.dependency_count} dependencies)\n"
            )
            _display_vulns(report, severity)

            # ── FIX ───────────────────────────────────────────────
            console.print()
            with Progress(
                SpinnerColumn("dots"),
                TextColumn("[bold]{task.description}"),
                TimeElapsedColumn(),
                console=console,
                transient=False,
            ) as progress:
                task = progress.add_task(
                    f"[2/3] AI agent analyzing and fixing vulnerabilities...",
                    total=None,
                )
                agent = ViperAgent(config=cfg, project_dir=target_dir, verbose=verbose)
                result = asyncio.run(agent.run_fix(report))
                if result.success:
                    progress.update(
                        task,
                        description=f"[green][2/3] Agent complete ({result.iterations_used} iterations)",
                    )
                else:
                    progress.update(task, description="[red][2/3] Agent failed")

            if not result.success:
                console.print(f"\n[red]Agent failed:[/red] {result.summary}")
                console.print(
                    f"[yellow]Completed {cycle - 1} successful cycle(s), "
                    f"{total_fixed} vulnerabilities addressed.[/yellow]"
                )
                raise typer.Exit(1)

            console.print(f"\n  [green]Agent done:[/green] {result.summary}")
            if result.changes:
                for change in result.changes:
                    console.print(f"    [dim]->[/dim] {change.path}")
            all_changes.extend(result.changes)

            # ── VALIDATE ──────────────────────────────────────────
            console.print()
            with Progress(
                SpinnerColumn("dots"),
                TextColumn("[bold]{task.description}"),
                TimeElapsedColumn(),
                console=console,
                transient=True,
            ) as progress:
                progress.add_task(
                    "[3/3] Re-scanning to validate fixes...", total=None
                )
                try:
                    validation_report = SnykParser.run_scan(
                        project_dir=target_dir,
                        snyk_token=cfg.snyk.token or None,
                        org=cfg.snyk.org or None,
                    )
                except ViperError as e:
                    console.print(
                        f"[yellow]Validation scan error (fixes may still be valid):[/yellow] {e}"
                    )
                    break

            remaining = SnykParser.filter_by_severity(
                validation_report, Severity(sev_threshold)
            )
            remaining = SnykParser.deduplicate(remaining)
            fixed_this_cycle = len(vulns) - len(remaining)
            total_fixed += max(fixed_this_cycle, 0)

            if not remaining:
                console.print(
                    Panel(
                        "[bold green]All vulnerabilities resolved![/bold green]",
                        border_style="green",
                    )
                )
                break

            console.print(
                f"  [yellow]{len(remaining)} vulnerabilities remaining[/yellow] "
                f"([green]{fixed_this_cycle} fixed[/green] this cycle)"
            )

            if fixed_this_cycle <= 0:
                console.print(
                    "\n[red]No progress made this cycle — stopping to avoid infinite loop.[/red]"
                )
                break

        else:
            console.print(
                f"\n[yellow]Reached max cycles ({max_cycles}). "
                f"Some vulnerabilities may remain.[/yellow]"
            )

        # ── SUMMARY ───────────────────────────────────────────
        elapsed = time.time() - start_time
        minutes = int(elapsed // 60)
        seconds = int(elapsed % 60)

        summary_table = Table(show_header=False, box=None, padding=(0, 2))
        summary_table.add_column(style="bold")
        summary_table.add_column()
        summary_table.add_row("Cycles completed", str(min(cycle, max_cycles)))
        summary_table.add_row("Vulnerabilities fixed", str(total_fixed))
        summary_table.add_row("Files modified", str(len(all_changes)))
        summary_table.add_row("Duration", f"{minutes}m {seconds}s")

        if all_changes:
            files = "\n".join(f"  {c.path}" for c in all_changes)
            summary_table.add_row("Changed files", files)

        console.print()
        console.print(Panel(summary_table, title="[bold]Summary[/bold]", border_style="cyan"))

    except ViperError as e:
        console.print(f"[red]Error:[/red] {e}")
        raise typer.Exit(1)


if __name__ == "__main__":
    app()
